### ISSUE TITLE
ID::blackbox is not defined

### ISSUE THREAD

**Issue by Rachus** [ghdl/ghdl-yosys-plugin#151]
When trying to compile the current git version (98f4594b67ef650b115653185022e46876fb08ce), the compilation fails with

`make
yosys-config --exec --cxx -c --cxxflags -o ghdl.o src/ghdl.cc -fPIC -DYOSYS_ENABLE_GHDL -I/home/un12ajek/Projects/ghdl/prefix/include -O
src/ghdl.cc: In function ‘void import_module(Yosys::RTLIL::Design*, GhdlSynth::Module)’:
src/ghdl.cc:634:30: error: ‘ID’ has not been declared
   module->set_bool_attribute(ID::blackbox);
                              ^~
src/ghdl.cc:654:59: error: no match for call to ‘(Yosys::hashlib::pool<Yosys::RTLIL::IdString>) (std::__cxx11::string)’
    module->avail_parameters(to_str(get_param_name(m, idx)));
                                                           ^
src/ghdl.cc:992:12: error: ‘struct Yosys::RTLIL::Module’ has no member named ‘addModFloor’; did you mean ‘addMod’?
    module->addModFloor(to_str(iname), IN(0), IN(1), OUT(0), id == Id_Smod);
            ^~~~~~~~~~~
            addMod
make: *** [Makefile:24: ghdl.o] Error 1
`

ID::blackbox was introduced in 38308d94658dc83856691fdb4bb6ad1ace8dc01a (ghdl.cc: handle attributes on output ports). I assume that maybe a file that defines ID could have been forgotten. Can someone maybe have a look if that's the case?

Regarding the other two errors: Can the plugin still be built with Yosys 0.8 or is a newer version required?

Edit: Is maybe also ID::blackbox only defined in a newer Yosys installation?

**Comment by Rachus** [comment]
Okay, sorry for the noise. It's fixed with a current yosys installation.
